reuse App on displayForm
atk4/login pull request #42
Opened 2020-05-13 09:19 UTC by abbadon1334

The old way to display an exception or a login form was to stop the current App and create a new one.
I manage to reuse the App, fix phpunit, remove deprecated code and do some cleanup.

2020-05-13 09:40 UTC, PhilippGrashoff commented on demos/wizard.php
>  class wizard extends App
Should be Uppercase

2020-05-13 09:40 UTC, PhilippGrashoff commented on demos/wizard.php
> +$wizard = $app->add('Wizard');
In the other files, you used ::addTo(). Would be great to have it here too to have demo code consistent

2020-05-14 13:17 UTC, DarkSide666 requested changes
Please address @PhilippGrashoff comments. Besides that looks good to me.

2020-05-15 10:03 UTC, DarkSide666 approved these changes
Now is good

2020-05-15 10:03 UTC, merged